[workspace]
resolver = "3"
members = [
  "axum_duper",
  "duper",
  "duper-js-wasm/rust",
  "duper-python",
  "duper_uniffi",
  "duper_website",
  "serde_duper",
  "serde_duper_macros",
]

[profile.release]
lto = true
strip = "debuginfo"
