[package]
name = "duper_lsp"
description = "LSP implementation for Duper."
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["Eric Rodrigues Pires <eric@eric.dev.br>"]
repository = "https://github.com/EpicEric/duper"
homepage = "https://duper.dev.br"
readme = "README.md"
publish = false

[dependencies]
async-lsp = { version = "0.2.2", features = ["tokio"] }
futures = "0.3.31"
lsp-types = "0.95.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = { version = "0.7.17", features = ["compat"] }
topiary-core = "0.7.1"
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
tree-sitter = "0.25.10"
tree-sitter-duper = { path = "../tree-sitter-duper" }
