rust:
  directory: ../duper_uniffi
  manifestPath: Cargo.toml

web:
  manifestPath: rust/Cargo.toml
  manifestPatchFile: Cargo.patch.toml
  wasmCrateName: duper-js-wasm
  workspace: true
  target: bundler
