[target.aarch64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.wasm32-unknown-unknown]
rustflags = ["-Copt-level=s"]
