id = "duper"
name = "Duper"
version = "0.0.1"
authors = ["Eric Rodrigues Pires <eric@eric.dev.br>"]
description = "Duper support for Zed."
repository = "https://github.com/EpicEric/duper"
schema_version = 1

[grammars.duper]
repository = "https://github.com/EpicEric/duper"
rev = "46c21fc9b285a880f5690acb00bb8cbf3ae0708c"
path = "tree-sitter-duper"

[language_servers.duper_lsp]
name = "duper_lsp"
language = "Duper"
