name: "[Release] Build @duper-js/wasm package"

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_VERSION: "1.91.1"
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_TEST_DEBUG: "0"
  NODE_VERSION: "20"
  BINARYEN_VERSION: "124"
  WASM_BINDGEN_VERSION: "0.2.100"

jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true
      - name: Fetch MSRV and add target
        run: |
          rustup toolchain install ${RUST_VERSION}
          rustup override set ${RUST_VERSION}
          rustup target add wasm32-unknown-unknown
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Install wasm-bindgen
        uses: taiki-e/install-action@a24ba45235ed716ff76646268742990dc9458860 # v2.62.42
        with:
          tool: wasm-bindgen@${{ env.WASM_BINDGEN_VERSION }}
      - name: Install wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_${BINARYEN_VERSION}/binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz -o binaryen.tar.gz
          tar -xzf binaryen.tar.gz
          mv binaryen-version_${BINARYEN_VERSION} binaryen
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies and build
        working-directory: duper-js-wasm
        run: |
          npm install
          npm run build:release
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist-duper-js-wasm
          path: duper-js-wasm/dist

  release:
    name: Release @duper-js/wasm
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: dist-x86_64-unknown-linux-gnu
          path: duper-js-wasm/dist
      - run: |
          ls -al ./duper-js-wasm/dist

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        working-directory: duper-js-wasm
        run: |
          npm publish --access public
