description: Release crate

on:
  push:
    tags:
      - "axum_duper@*.*.*"
      - "duper@*.*.*"
      - "duper_lsp@*.*.*"
      - "duperfmt@*.*.*"
      - "duperq@*.*.*"
      - "serde_duper@*.*.*"
      - "serde_duper_macros@*.*.*"
      - "tracing_duper@*.*.*"
      - "tree-sitter-duper@*.*.*"

jobs:
  publish-to-crates-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true
      - name: Authenticate
        uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth
      - name: Publish axum_duper
        if: startsWith(github.ref_name, 'axum_duper@')
        run: cargo publish -p axum_duper
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish duper
        if: startsWith(github.ref_name, 'duper@')
        run: cargo publish -p duper
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish duper_lsp
        if: startsWith(github.ref_name, 'duper_lsp@')
        run: cargo publish -p duper_lsp
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish duperfmt
        if: startsWith(github.ref_name, 'duperfmt@')
        run: cargo publish -p duperfmt
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish duperq
        if: startsWith(github.ref_name, 'duperq@')
        run: cargo publish -p duperq
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish serde_duper
        if: startsWith(github.ref_name, 'serde_duper@')
        run: cargo publish -p serde_duper
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish serde_duper_macros
        if: startsWith(github.ref_name, 'serde_duper_macros@')
        run: cargo publish -p serde_duper_macros
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish tracing_duper
        if: startsWith(github.ref_name, 'tracing_duper@')
        run: cargo publish -p tracing_duper
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Publish tree-sitter-duper
        if: startsWith(github.ref_name, 'tree-sitter-duper@')
        run: cargo publish -p tree-sitter-duper
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
