on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  RUST_VERSION: "1.92.0"
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_TEST_DEBUG: "0"
  NODE_VERSION: "24"
  BINARYEN_VERSION: "124"
  WASM_BINDGEN_VERSION: "0.2.100"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      - name: Fetch Rust and add target
        run: |
          rustup toolchain install ${RUST_VERSION}-x86_64-unknown-linux-gnu
          rustup override set ${RUST_VERSION}-x86_64-unknown-linux-gnu
          rustup target add wasm32-unknown-unknown
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Install wasm-bindgen
        uses: taiki-e/install-action@a24ba45235ed716ff76646268742990dc9458860 # v2.62.42
        with:
          tool: wasm-bindgen@${{ env.WASM_BINDGEN_VERSION }}
      - name: Install wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_${BINARYEN_VERSION}/binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz -o binaryen.tar.gz
          tar -xzf binaryen.tar.gz
          mv binaryen-version_${BINARYEN_VERSION} binaryen
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Install Node dependencies and build
        working-directory: ./duper_website
        run: |
          bun install
          bun wasm:build
          bun wasm:bindgen
          ../binaryen/bin/wasm-opt -Os ./pkg/duper_website_bg.wasm -o ./pkg/duper_website_bg.wasm
          bun run build
      - name: Deploy to Sandhole
        if: github.ref == 'refs/heads/main'
        uses: up9cloud/action-rsync@e5f52e6a78755fa0ddbfd2d52f61de0490661665 # master
        env:
          SOURCE: ./duper_website/docs/.vitepress/dist/
          HOST: ${{ secrets.WEBSITE_SSH_HOST }}
          PORT: ${{ secrets.WEBSITE_SSH_PORT }}
          USER: ${{ secrets.WEBSITE_SSH_USER }}
          KEY: ${{ secrets.WEBSITE_SSH_KEY }}
          TARGET: ${{ secrets.WEBSITE_SSH_TARGET }}
